name: Deploy to Vercel


on:
  push:
    branches:
      - main   # only run on pushes to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install dependencies
        run: npm install

      

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Verify Vercel Token
        run: vercel whoami --token $VERCEL_TOKEN
      - name: Deploy to Vercel
        run: vercel --prod --yes --token $VERCEL_TOKEN