name: Run Tests

on:
  push:
    branches-ignore:
      - main         # ❌ Skip pushes to main
  pull_request:
    branches:
      - main         # ✅ Run tests when PR targets main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
